server:
  requestLog:
    appenders:
      - type: file
        currentLogFilename: ${ARLAS_TAGGER_ACCESS_LOG_FILE:-arlas-tagger-access.log}
        archivedLogFilenamePattern: ${ACCESS_TAGGER_LOG_FILE_ARCHIVE:-arlas-tagger-access-%d.log.gz}
  registerDefaultExceptionMappers: false
  type: simple
  rootPath: ${ARLAS_TAGGER_PREFIX:-/arlas_tagger}
  applicationContextPath: ${ARLAS_TAGGER_APP_PATH:-/}
  adminContextPath: ${ARLAS_TAGGER_ADMIN_PATH:-/admin}
  connector:
    type: http
    port: ${ARLAS_TAGGER_PORT:-9998}
  maxThreads: ${ARLAS_TAGGER_MAX_THREADS:-1024}
  minThreads: ${ARLAS_TAGGER_MIN_THREADS:-8}
  maxQueuedRequests: ${ARLAS_TAGGER_MAX_QUEUED_REQUESTS:-1024}

########################################################
############ ARLAS TAGGER                ###############
########################################################
swagger: # Configuration of SWAGGER for generating documentation and APIs
  resourcePackage: io.arlas.tagger.rest # The java package to process for extracting the APIs

kafka_configuration:
  kafka_consumer_poll_timeout: ${KAFKA_CONSUMER_POLL_TIMEOUT:-100}
  kafka_batch_size: ${KAFKA_BATCH_SIZE:-10}
  kafka_bootstrap_servers: ${KAFKA_BROKERS:-localhost:9092}
  kafka_consumer_group_id_tagref_log: ${KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG:-tagref_log_consumer_group}
  kafka_consumer_group_id_execute_tags: ${KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS:-execute_tags_consumer_group}
  kafka_topic_tagref_log: ${KAFKA_TOPIC_TAGREF_LOG:-tagref_log}
  kafka_topic_execute_tags: ${KAFKA_TOPIC_EXECUTE_TAGS:-execute_tags}
  kafka_extra_properties: ${KAFKA_EXTRA_PROPS:-}

elastic_configuration:
  elastic_nodes: ${ARLAS_ELASTIC_NODES:-localhost:9300}
  elastic_sniffing: ${ARLAS_ELASTIC_SNIFFING:-false}
  elastic_cluster: ${ARLAS_ELASTIC_CLUSTER:-elasticsearch}

arlas_collections_configuration:
  arlas_index:  ${ARLAS_COLLECTION_INDEX:-.arlas}
  arlas_cache_size: ${ARLAS_COLLECTION_CACHE_SIZE:-1000}
  arlas_cache_timeout: ${ARLAS_COLLECTION_CACHE_TIMEOUT:-60}

tagging_status_timeout: ${TAGGING_STATUS_TIMEOUT:-3600000}

arlas_cors_enabled: ${ARLAS_TAGGER_CORS_ENABLED:-true}




