version: '3'

services:
  arlas-tagger:
    build:
      context: ../../.
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only-tagger}
    image: gisaia/arlas-tagger:${ARLAS_TAGGER_VERSION:-latest}
    container_name: arlas-tagger
    environment:
      - ARLAS_ELASTIC_CLUSTER="docker-cluster"
      - ARLAS_ELASTIC_NODES=elasticsearch:9300
      - ARLAS_SERVER_NODE=${ARLAS_SERVER_NODE}
      - ARLAS_TAGGER_PREFIX=${ARLAS_TAGGER_PREFIX:-/arlas_tagger}
      - ARLAS_TAGGER_APP_PATH=${ARLAS_TAGGER_APP_PATH:-/}
      - KAFKA_COMMIT_MAX_RETRIES="${KAFKA_COMMIT_MAX_RETRIES:-3}"
      - KAFKA_BATCH_SIZE_TAGREF="${KAFKA_BATCH_SIZE_TAGREF:-1}"
      - KAFKA_BATCH_SIZE_TAGEXEC="${KAFKA_BATCH_SIZE_TAGEXEC:-10}"
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG="${KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG:-tagref_log_consumer_group}"
      - KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS="${KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS:-execute_tags_consumer_group}"
      - KAFKA_TOPIC_TAGREF_LOG="${KAFKA_TOPIC_TAGREF_LOG:-tagref_log}"
      - KAFKA_TOPIC_EXECUTE_TAGS="${KAFKA_TOPIC_EXECUTE_TAGS:-execute_tags}"
      - KAFKA_EXTRA_PROPS="${KAFKA_EXTRA_PROPS}"
    depends_on:
      - kafka
    ports:
      - 19998:9998
    command: ["/opt/app/wait-for-tagger-deps.sh $$KAFKA_BROKERS $$ARLAS_ELASTIC_NODES $$ARLAS_SERVER_NODE"]
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      LOG4J_LOGGER_KAFKA: INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KAFKA_DATADIR}:/tmp/kafka-logs
