###################
# PACKAGING STAGE #
###################
FROM openjdk:8-jre-alpine

# install script dependencies
RUN apk add --update bash netcat-openbsd curl && rm -rf /var/cache/apk/*

# application placed into /opt/app
WORKDIR /opt/app
ADD arlas-tagger/target/arlas-tagger*.jar /opt/app/arlas-tagger.jar
ADD conf/configuration.yaml /opt/app/configuration.yaml
ADD docker/docker-resources/wait-for-tagger-deps.sh /opt/app/wait-for-tagger-deps.sh
ADD docker/docker-resources/wait-for-elasticsearch.sh /opt/app/wait-for-elasticsearch.sh
ADD docker/docker-resources/start.sh /opt/app/start.sh
EXPOSE 9998

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl http://localhost:9998/admin/healthcheck | grep -v "\"healthy\":false" || exit 1

CMD /opt/app/start.sh
