###################
# PACKAGING STAGE #
###################
FROM gisaia/arlas-openjdk:17-distroless

# application placed into /opt/app
WORKDIR /opt/app
ADD arlas-tagger/target/arlas-tagger*.jar /opt/app/arlas-tagger.jar
ADD conf/configuration.yaml /opt/app/configuration.yaml
EXPOSE 9998

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl http://localhost:9998/admin/healthcheck | grep -v "\"healthy\":false" || exit 1

ENV JDK_JAVA_OPTIONS="-Xmx512m -XX:+ExitOnOutOfMemoryError"
CMD ["arlas-tagger.jar", "server", "/opt/app/configuration.yaml"]
