version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.14.2}
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - node.name=docker-node
      - cluster.initial_master_nodes=docker-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
#      - /var/lib/elasticsearch:/usr/share/elasticsearch/data
      - ${ELASTIC_DATADIR}:/usr/share/elasticsearch/data
    ports:
      - 19200:9200
