version: '3'

services:
  arlas-tagger:
    build:
      context: ../../.
      dockerfile: ${DOCKERFILE:-docker/docker-files/Dockerfile-package-only}
    image: gisaia/arlas-tagger:${ARLAS_TAGGER_VERSION:-latest}
    container_name: arlas-tagger
    environment:
      # ES
      - ARLAS_ELASTIC_NODES=${ARLAS_ELASTIC_NODES:-elasticsearch:9200}
      - ARLAS_ELASTIC_SNIFFING=${ARLAS_ELASTIC_SNIFFING:-false}
      - ARLAS_ELASTIC_ENABLE_SSL=${ARLAS_ELASTIC_ENABLE_SSL:-false}
      - ARLAS_ELASTIC_SKIP_MASTER="${ARLAS_ELASTIC_SKIP_MASTER:-true}"
      - ARLAS_ELASTIC_CREDENTIALS=${ARLAS_ELASTIC_CREDENTIALS}
      # ARLAS SERVER
      - ARLAS_SERVER_NODE=${ARLAS_SERVER_NODE}
      - ARLAS_COLLECTION_INDEX=${ARLAS_COLLECTION_INDEX:-.arlas}
      # TAGGER Server
      - ARLAS_TAGGER_PORT=${ARLAS_TAGGER_PORT:-9998}
      - ARLAS_TAGGER_PREFIX=${ARLAS_TAGGER_PREFIX:-/arlas_tagger}
      - ARLAS_TAGGER_APP_PATH=${ARLAS_TAGGER_APP_PATH:-/}
      - ARLAS_TAGGER_ADMIN_PATH=${ARLAS_TAGGER_ADMIN_PATH:-/admin}
      # KAFKA
      - KAFKA_COMMIT_MAX_RETRIES=${KAFKA_COMMIT_MAX_RETRIES:-3}
      - KAFKA_CONSUMER_POLL_TIMEOUT=${KAFKA_CONSUMER_POLL_TIMEOUT:-100}
      - KAFKA_BATCH_SIZE_TAGREF=${KAFKA_BATCH_SIZE_TAGREF:-1}
      - KAFKA_BATCH_SIZE_TAGEXEC=${KAFKA_BATCH_SIZE_TAGEXEC:-10}
      - KAFKA_NUMBER_TAGEXEC=${KAFKA_NUMBER_TAGEXEC:-12}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-kafka:9092}
      - KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG=${KAFKA_CONSUMER_GROUP_ID_TAGREF_LOG:-tagref_log_consumer_group}
      - KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS=${KAFKA_CONSUMER_GROUP_ID_EXECUTE_TAGS:-execute_tags_consumer_group}
      - KAFKA_TOPIC_TAGREF_LOG=${KAFKA_TOPIC_TAGREF_LOG:-tagref_log}
      - KAFKA_TOPIC_EXECUTE_TAGS=${KAFKA_TOPIC_EXECUTE_TAGS:-execute_tags}
      - KAFKA_EXTRA_PROPS=${KAFKA_EXTRA_PROPS}
      # TAGGING
      - TAGGING_STATUS_TIMEOUT=${TAGGING_STATUS_TIMEOUT:-3600000}
      # LOGGING
      - ARLAS_LOGGING_LEVEL=${ARLAS_LOGGING_LEVEL:-INFO}
      - ARLAS_LOGGING_CONSOLE_LEVEL=${ARLAS_LOGGING_CONSOLE_LEVEL:-INFO}
      - ARLAS_LOGGING_FILE=${ARLAS_LOGGING_FILE:-arlas.log}
      - ARLAS_LOGGING_FILE_LEVEL=${ARLAS_LOGGING_FILE_LEVEL:-INFO}
      - ARLAS_AUTH_POLICY_CLASS="${ARLAS_AUTH_POLICY_CLASS:-io.arlas.filter.impl.NoPolicyEnforcer}"
      - ARLAS_AUTH_PERMISSION_URL="${ARLAS_AUTH_PERMISSION_URL:-http://arlas-iam-server:9990/arlas_iam_server/permissions}"
      - ARLAS_AUTH_CERT_URL="${ARLAS_AUTH_CERT_URL}"
      - ARLAS_CACHE_FACTORY_CLASS="${ARLAS_CACHE_FACTORY_CLASS:-io.arlas.tagger.impl.HazelcastCacheFactory}"
      - ARLAS_CACHE_TIMEOUT="${ARLAS_CACHE_TIMEOUT:-5}"
    ports:
      - 19998:9998
    volumes:
      - ${ARLAS_AUTH_LOCAL_CERT_FILE:-/tmp}:${ARLAS_AUTH_CERT_FILE:-/opt/app/arlas.pem}:ro
